server:
  port: 7072

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:7074/eureka/

spring:
  application:
    name: olive-foundation-server
    
  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

# TODO: This config can be moved to application-dev.yml
security:
  oauth2:
    resource:
      jwt:
        key-value: ---- BEGIN SSH2 PUBLIC KEY ----AAAAB3NzaC1yc2EAAAADAQABAAABAQDBf1jZNlhSttQv8NsUxn6iRgpRvMhQ9qZZ6cb/GzwDZTNuh9XGW6YOwoOtMJYFhOzh8midW/qs9I00o+SF0ZnyZaqC+mNhEW4++HpCM2Y30Jv64b/kGPYuXQpsHA7Iu4TsIOZA6TalHStd8VwiHmm0GZZnMYUGJFUAAIzBoC2nzQiMUWxEa8Brh8fbQ1v5Ox5Zh36tTbCm8Y0vSttA2XcfnZsXT8MsvFD79rtyUrSik1AxsprU77MUARWYrcGVuNRYwHqW5xriTvZZiMRwFzrgIoCYuCpCB0p/SIxrnw+MfHMZ4xgZGX4XVIHHd/LraRVArwwmWOnJHpxzGlQ9TWW5---- END SSH2 PUBLIC KEY ----

      
logging:
  file:
    name: ./logs/olive-foundation-server.log
