server:
  port: 7071

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:7074/eureka/

spring:
  application:
    name: olive-auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

config:
  oauth2:
    privateKey: -----BEGIN ENCRYPTED PRIVATE KEY-----MIIFHzBJBgkqhkiG9w0BBQ0wPDAbBgkqhkiG9w0BBQwwDgQI5aAgetfHfJICAggAMB0GCWCGSAFlAwQBKgQQRYbspzaNib6kx+HIFlTgZgSCBNAleLOL2seUPjEhJuKte22yl0dFCjOtXAy8SttBCVIcV/ctRNvDi4zbB5fKUubKTKSYuuKTPy2RuIQIsxUtCBrwBwpYP520G9SXROrYslJ4gEfJOFZ5SmDXQGDjXVJbM3dLmiGLPDdxjNT81pOoRwpvU4w1+Ve4K9h+P8MkA7v8SyyfnWppdwN7/bOvg8/mf9XxYUPF4lk68Poe7Ec6iObZhjRnPS7BU1gKpVmyp/32/6DSnIrUM8yr45Q23L7aHYO/l0mmO0VlTkE0qSM8HU8JYhlOEbiQRF9/36Q+rCvTTvwt3R0jJODvIuexm6ZB5MrdFmV6xUUJtzgbcAhVLI4TOeyqUZhIvz8cvqEwnaF1OsIQtWjB85VlmydaF++tMaQp4Fyo09NJ8x1FUV482NcbWEx6YnvLgxGw1cbrB1/Hnx1lLV9CCBc766THymTdTfjSwM6ov7WuwxlGeivXvXN+qeePNWutZ/B/nJuBD5dcsSQzyGH3b2brd226lV77Abhoq+MpRSEVI48X6fGdE574HUr3xwI4kFWmCOwDW050/or1WozWRVhACqMHMgm3k9DdKAjHqHjKnLdVC5aXmXvfhIuJoOqcWYSyVUevjwUMEuDIIWxY0p7yLYfO64V+ZyAHW9m/4Fg7TWA9QvQ0e/KhSZrlwLILhkOC8N9+OMYOONMP8RKjzfpEstuX307Dxq8SUMoobhyRu3n/bLUPVXZaPxrvZqWimbmkezhIaOYADAGRcUQTPBpcD2B6axQatnC/QpiSMibGfvsknciRi6o12cZKjg1Cl4NE3vIgAFVKo9w220TpZvuDYqhgsl5+1BLZz1bCzQwEer2HHnqRofKcfsRDSZaC4QXoTjDsRILudUQsAqEkmLgBxwN68CCc+c5g8Ly4oVdfVJDm0sUzafCD7xD0GzmO8Kc+sAwqGw4Lf5BfGMmNSrE+bSNIO1xoD07hkR0s9tq2jXqjlFNNu91HbKfxQ7cQrtwy32WwBDVEpuo7A3fWx6yn6SGqL+E9KslUVcau13dIQq2bsTnCc+3S/n6X4zgiu2JswpyrSh7s8T5XzFuD+KJAQlK7Tds3TQhNIGR+bj2Pm6okQsMfkVoa+08fcEbMnfwbzIcSqtWr5ZjfsOgJ8bpv6KpTwWkcSJ6JJJtQ5v6tjqb084m0xNEU6pV+pIeYz1bEupX/MwrMbmjUn1kYmZBc1uNOadEE3BPvSrmPU91lGUIDYzkykbH/vVy+doFJNhYElVYKsqfaCMU9RR6QJaDtAAaDVhKzf42Tdtbna+iLUaj6Q+pJfow5O2H3Tro18iUqRr/UN9Wwd+r2V//ogXNNnlTlo8vc22j75j6FQPdTqMnra4YSWZNeVfU6Rlh7n9IA2qmw2NzYAu9YGLFDF1wvBpnF/Ok2zDHigjqZHh2gesyi6MHTypUITpmbncnCjieVp8l7uEjSzq5V5vLizVVpGmQ1pjRMjbvDiR2SfXGUL7n1TWgF2qxbb5nAl3D2cmLOK3Vz2IPqj8yy+7h7Kio/kWS7Ft2XEeCuq4JD3NuZwRrExKrV34zXnBIz176KDs//ZWDs8cog7GiQFYyXgcXkx/StFz61JvOu3VRvYp4gtWmqkYepmsXvvRzhJz9pMs4Z0fGf+ppDjA==-----END ENCRYPTED PRIVATE KEY-----
    publicKey: ---- BEGIN SSH2 PUBLIC KEY ----AAAAB3NzaC1yc2EAAAADAQABAAABAQDBf1jZNlhSttQv8NsUxn6iRgpRvMhQ9qZZ6cb/GzwDZTNuh9XGW6YOwoOtMJYFhOzh8midW/qs9I00o+SF0ZnyZaqC+mNhEW4++HpCM2Y30Jv64b/kGPYuXQpsHA7Iu4TsIOZA6TalHStd8VwiHmm0GZZnMYUGJFUAAIzBoC2nzQiMUWxEa8Brh8fbQ1v5Ox5Zh36tTbCm8Y0vSttA2XcfnZsXT8MsvFD79rtyUrSik1AxsprU77MUARWYrcGVuNRYwHqW5xriTvZZiMRwFzrgIoCYuCpCB0p/SIxrnw+MfHMZ4xgZGX4XVIHHd/LraRVArwwmWOnJHpxzGlQ9TWW5---- END SSH2 PUBLIC KEY ----

logging:
  file:
    name: ./logs/olive-auth-server.log
