server:
  port: 7070

spring:
  application:
    name: olive-gateway-server    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    
#      routes:
#        - id: foundation
#          uri: 'http://localhost:7072'
#          predicates:
#            - Path=/api/org/**


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"
          
#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://localhost:7074/eureka/
      
logging:
  file:
    name: ./logs/olive-gateway-server.log
    

