server:
  port: 7073

spring:
  application:
    name: olive-util-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"
          
#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 5
#    service-url:
#      defaultZone: http://localhost:7074/eureka/
      
logging:
  file:
    name: ./logs/olive-util-server.log
