server:
  port: 7072

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:7074/eureka/

spring:
  application:
    name: olive-foundation-server
    
  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:7071/oauth/check_token
    client:
      client-id: olive@carmelsolutions
      client-secret: "{bcrypt}$2y$12$Hgfp8LOiIIoCmXl3j.FD6OcIPW3kk7dHG10.0LHhV8mrbSa1wn9OW"
      
logging:
  file:
    name: ./logs/olive-foundation-server.log
